#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2
id = "nidimages"
name = "Nidimages"
description.en = "Photo sharing web app to keep your family and friends connected with your adventures and memories"
description.fr = "Application web de partage des photos permettant à la famille et aux ami.e.s de suivre tes aventures"

version = "1.4~ynh1"

maintainers = ["sitegui"]

[upstream]
license = "AGPL-3.0-only"
demo = "https://demo.nidimages.sitegui.dev/"
code = "https://git.sitegui.dev/sitegui/nidimages"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = true

disk = "100M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://git.sitegui.dev/sitegui/nidimages/releases/download/v1.4/nidimages-x86_64-unknown-linux-musl.zip"
    amd64.sha256 = "70ecac7bca792f36f157b52f2dff6e152b7f5cc5888b794ac99ca0b39a4b03e9"
    arm64.url = "https://git.sitegui.dev/sitegui/nidimages/releases/download/v1.4/nidimages-aarch64-unknown-linux-musl.zip"
    arm64.sha256 = "2ff5fb8a4299675782748e7947b4c58b2bf4ddf7ee0f3a0c5315bfb12ee6d18b"
    in_subdir = false
    autoupdate.strategy = "latest_forgejo_release"
    autoupdate.asset.amd64 = "nidimages-x86_64-unknown-linux-musl\\.zip"
    autoupdate.asset.arm64 = "nidimages-aarch64-unknown-linux-musl\\.zip"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "ffmpeg, libimage-exiftool-perl"
